name: CI

on:
  workflow_call:
    inputs:
      requirements_file:
        description: "Name of the file containing python requirements"
        required: true
        default: "requirements.txt"
        type: string
      test_dir:
        description: "Directory for tests"
        required: true
        type: string
     

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ${{ inputs.requirements_file }}"

      - name: Show packages
        run: |
          pip freeze

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run tests using pytest
        run: pytest ${{ inputs.requirements_file }}
