name: test

on:
  workflow_dispatch:
     

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo variable
        run: |
            name=$(yq eval '.environments.default.workflows[0].name' "dbx_deployment.yml.j2")
            echo $name